### ISSUE TITLE
IlluminaHumanMethylationEPICanno.ilm10b2.hg19

### ISSUE THREAD

**Issue by QianhuiWan** [timpeters82/DMRcate-release#1]
Hi Tim, is it posible to update `IlluminaHumanMethylationEPICanno.ilm10b2.hg19` to `IlluminaHumanMethylationEPICanno.ilm10b4.hg19`? Thank you!

**Comment by timpeters82** [comment]
Hi Qianhui,

Thanks for the heads up. I'll make sure it's included in the next release.

Cheers,
Tim

**Comment by QianhuiWan** [comment]
Hi Tim, thank you so much!

Best regards
Qianhui Wan
PhD candidate
Obstetrics and Gynaecology
Adelaide Medical School
Robinson Research Institute
Level 6, AHMS Building
The University of Adelaide, SA, Australia 5000
Email: qianhui.wan@adelaide.edu.au<mailto:qianhui.wan@adelaide.edu.au>
Ph: +61 8 8313 7485
[cid:image001.jpg@01D3AB24.E66EA6A0]
