### ISSUE TITLE
cpg.annotate bug

### ISSUE THREAD

**Issue by lucassalas** [timpeters82/DMRcate-release#2]
Hi @timpeters82 ,
I was working with DMRcate today, and I realized one minor issue in the cpg.annotate function. On line 22:
`nsig <- sum(tt$adj.P.Val < 0.05)`
If the matrix of beta-values had some NA rows, the function crashes as it generates a missing value for the if-else condition.
I changed it manually to
`nsig <- sum(tt$adj.P.Val < 0.05, na.rm=TRUE)` and the issue was solved.
I decide to ask you if there is any other reason to avoid that option in your code?
I hope that helps.

**Comment by timpeters82** [comment]
Hi Lucas,

I'd preemptively get rid of any rows in your matrix that have NAs in the first place, prior to running `cpg.annotate()`. The reason I wouldn't change it is that it's important that to my mind the full rank model be fit to each CpG, as per best practice use of limma.

See Gordon's comments on missing values here: https://support.bioconductor.org/p/21469/. Note that `cpg.annotate()` has an ellipsis argument that allows extra `limma::lmFit()` arguments to be passed to it, which would allow you flexibility in treating your NAs.

Cheers,
Tim

**Comment by lucassalas** [comment]
Hi @timpeters82  ,

Thank you for the answer. That makes sense to me, but I preferred to ask (so you will have it documented, if anybody else asks again in the future).
I was just curious about the behavior of that on cpg.annotate and dmrcate. limma just set the warnings as expected in Gordon's thread, but when summing the line 22 in DMRcate reported NA and the following for-loop stopped. 
It makes sense to keep as many CpGs as possible to calculate the regions, limma will still output the warning about the missing values too, but stopping the function is also an alternative. I would suggest adding a warning message that the matrix includes NA's, (see the current message below), or adding a line on the manual stating that this is the expected behavior for the user. 

`## ----libr, message=FALSE, warning=FALSE---------------------------------------
library(DMRcate)

## ----tcells, message=FALSE----------------------------------------------------
library(ExperimentHub)
eh <- ExperimentHub()
FlowSorted.Blood.EPIC <- eh[["EH1136"]]  
tcell <- FlowSorted.Blood.EPIC[,colData(FlowSorted.Blood.EPIC)$CD4T==100 | 
                                 colData(FlowSorted.Blood.EPIC)$CD8T==100]

## ----detpnorm-----------------------------------------------------------------
detP <- detectionP(tcell)
remove <- apply(detP, 1, function (x) any(x > 0.01))
tcell <- tcell[!remove,]
tcell <- preprocessFunnorm(tcell)
tcellms <- getM(tcell)

## ----filter, message=FALSE----------------------------------------------------
nrow(tcellms)
tcellms.noSNPs <- rmSNPandCH(tcellms, dist=2, mafcut=0.05)
nrow(tcellms.noSNPs)

## ----avearrays----------------------------------------------------------------
tcell$Replicate
tcell$Replicate[tcell$Replicate==""] <- tcell$Sample_Name[tcell$Replicate==""]
tcellms.noSNPs <- limma::avearrays(tcellms.noSNPs, tcell$Replicate)
tcell <- tcell[,!duplicated(tcell$Replicate)]
tcell <- tcell[rownames(tcellms.noSNPs),]
assays(tcell)[["M"]] <- tcellms.noSNPs
assays(tcell)[["Beta"]] <- ilogit2(tcellms.noSNPs)

## ----annotate, message=FALSE--------------------------------------------------
type <- factor(tcell$CellType)
design <- model.matrix(~type) 
tcell2<-getBeta(tcell)
tcell2[1,]<-NA
head(tcell2)
myannotation <- cpg.annotate("array", tcell2, arraytype = "EPIC",
                             analysis.type="differential", design=design, coef=2)
`
The output message is "Error in if (nsig == 0) { : missing value where TRUE/FALSE needed"

Thanks again for the follow-up. Feel free to disregard any of the comments above, and close the issue.

Cheers,

Lucas
